import random
import os
import numpy as np
from astroquery.vizier import Vizier, Conf
from astropy.coordinates import SkyCoord
import astropy.units as u

Conf.server = "vizier.china-vo.org"
OUT = r"C:\Users\sibop\Desktop\cosmos-source\src\lib\cosmos\quasars-real.ts"
os.makedirs(os.path.dirname(OUT), exist_ok=True)

print("Querying Milliquas (VII/280) via China-VO VizieR (z>0)...")
viz = Vizier(catalog="VII/280", row_limit=2500)
res = viz.query_constraints(z=">0")
t = res["VII/280/catalog"]
print("rows returned:", len(t), "cols:", [c for c in t.colnames])

rows = []
for r in t:
    zv = r["z"]
    if zv is np.ma.masked or zv is None:
        continue
    z = float(zv)
    if not (0.01 < z < 8):
        continue
    ra = float(r["RAJ2000"]); dec = float(r["DEJ2000"])
    if not np.isfinite(ra) or not np.isfinite(dec):
        continue
    name = str(r["Name"]).strip() or f"QSO J{int(ra*100):06d}{int(dec*100):+05d}"
    rows.append((name, ra, dec, z))

print("valid quasars with z:", len(rows))
random.seed(42)
sample = random.sample(rows, min(300, len(rows)))
print("sampled:", len(sample))

def to_gal(ra, dec):
    c = SkyCoord(ra=ra*u.deg, dec=dec*u.deg, frame="icrs")
    return round(c.galactic.l.deg, 3), round(c.galactic.b.deg, 3)

# Flat Lambda-CDM comoving distance from Planck18 parameters (no scipy needed).
# D_C = (c/H0) * ∫_0^z dz' / sqrt(Om*(1+z')^3 + Ode), with c/H0 in Mpc then -> ly.
_C_KMS = 299792.458
_H0 = 67.66          # km/s/Mpc (Planck18)
_OM = 0.30966        # matter density
_ODE = 0.68990       # dark-energy density (flat: Ok=0)
_MPC_TO_LY = 3.26156e6
try:
    _trapz = np.trapezoid
except AttributeError:
    _trapz = np.trapz
def comoving_ly(z):
    zs = np.linspace(0.0, z, max(64, int(z * 256)))
    ez = np.sqrt(_OM * (1.0 + zs) ** 3 + _ODE)
    integral = _trapz(1.0 / ez, zs)
    d_mpc = (_C_KMS / _H0) * integral
    return int(d_mpc * _MPC_TO_LY)

lines = []
for name, ra, dec, z in sample:
    l, b = to_gal(ra, dec)
    try:
        dly = comoving_ly(z)
    except Exception:
        continue
    note = f"全天实测类星体 · 红移 z={z:.3f}"
    lines.append(
        "  {\n"
        f"    n: {name!r},\n"
        f"    en: {name!r},\n"
        f"    z: {z:.4f},\n"
        f"    distLy: {dly},\n"
        f"    l: {l},\n"
        f"    b: {b},\n"
        f"    note: {note!r},\n"
        "  },"
    )

header = (
    "// Auto-generated by gen_quasars.py — real quasars from Milliquas (VizieR VII/280)\n"
    "// via astroquery + China-VO mirror (vizier.china-vo.org). Real RA/Dec/z; l/b derived\n"
    "// from ICRS with astropy, comoving distance from Planck18. Do not edit by hand.\n"
    "import type { QuasarData } from './universe-data';\n\n"
    "export const QUASARS_REAL: QuasarData[] = [\n"
)
footer = "\n];\n"

with open(OUT, "w", encoding="utf-8") as f:
    f.write(header + "\n".join(lines) + footer)
print("WROTE", OUT, "with", len(lines), "quasars")
