// One-off generator for P2-1: expands Western constellations from 15 to 88 and
// adds ~300 bright stars, sourced from the license-friendly d3-celestial dataset
// (raw.githubusercontent.com/ofrohn/d3-celestial). Run with: bun scripts/_gen_p21.ts
// Output: src/lib/cosmos/west-constellations.ts
import { writeFileSync } from "node:fs";

const ROOT = "scripts/_p21raw";
const lines = JSON.parse(
  (await import("node:fs")).readFileSync(`${ROOT}/constellations.lines.json`, "utf8"),
);
const stars = JSON.parse(
  (await import("node:fs")).readFileSync(`${ROOT}/stars.6.json`, "utf8"),
);

// 3-letter IAU id -> standard Chinese constellation name (中国天文学会 88 星座标准译名)
const CN: Record<string, string> = {
  And: "仙女座", Ant: "唧筒座", Aps: "天燕座", Aql: "天鹰座", Aqr: "宝瓶座",
  Ara: "天坛座", Ari: "白羊座", Aur: "御夫座", Boo: "牧夫座", CMa: "大犬座",
  CMi: "小犬座", CVn: "猎犬座", Cae: "雕具座", Cam: "鹿豹座", Cap: "摩羯座",
  Car: "船底座", Cas: "仙后座", Cen: "半人马座", Cep: "仙王座", Cet: "鲸鱼座",
  Cha: "蝘蜓座", Cir: "圆规座", Cnc: "巨蟹座", Col: "天鸽座", Com: "后发座",
  CrA: "南冕座", CrB: "北冕座", Crt: "巨爵座", Cru: "南十字座", Crv: "乌鸦座",
  Cyg: "天鹅座", Del: "海豚座", Dor: "剑鱼座", Dra: "天龙座", Equ: "小马座",
  Eri: "波江座", For: "天炉座", Gem: "双子座", Gru: "天鹤座", Her: "武仙座",
  Hor: "时钟座", Hya: "长蛇座", Hyi: "水蛇座", Ind: "印第安座", LMi: "小狮座",
  Lac: "蝎虎座", Leo: "狮子座", Lep: "天兔座", Lib: "天秤座", Lup: "豺狼座",
  Lyn: "天猫座", Lyr: "天琴座", Men: "山案座", Mic: "显微镜座", Mon: "麒麟座",
  Mus: "苍蝇座", Nor: "矩尺座", Oct: "南极座", Oph: "蛇夫座", Ori: "猎户座",
  Pav: "孔雀座", Peg: "飞马座", Per: "英仙座", Phe: "凤凰座", Pic: "绘架座",
  PsA: "南鱼座", Psc: "双鱼座", Pup: "船尾座", Pyx: "罗盘座", Ret: "网罟座",
  Scl: "玉夫座", Sco: "天蝎座", Sct: "盾牌座", Ser: "巨蛇座", Sex: "六分仪座",
  Sge: "天箭座", Sgr: "人马座", Tau: "金牛座", Tel: "望远镜座", TrA: "南三角座",
  Tri: "三角座", Tuc: "杜鹃座", UMa: "大熊座", UMi: "小熊座", Vel: "船帆座",
  Vir: "室女座", Vol: "飞鱼座", Vul: "狐狸座",
};

interface ConsOut {
  name: string;
  stars: [number, number, number][];
  lines: [number, number][];
}

const consOut: ConsOut[] = [];
for (const f of lines.features as any[]) {
  const id: string = f.id;
  const polys: number[][][] = f.geometry.coordinates; // array of polylines, each [[ra_deg,dec_deg],...]
  const verts: [number, number, number][] = [];
  const idx = new Map<string, number>();
  const linesArr: [number, number][] = [];
  const key = (ra: number, dec: number) => `${ra.toFixed(3)},${dec.toFixed(3)}`;
  const getIdx = (ra: number, dec: number): number => {
    const k = key(ra, dec);
    let i = idx.get(k);
    if (i === undefined) {
      i = verts.length;
      verts.push([
        Math.round((ra / 15) * 1e4) / 1e4,
        Math.round(dec * 1e4) / 1e4,
        3.0,
      ]); // ra_h, dec_deg, nominal mag
      idx.set(k, i);
    }
    return i;
  };
  for (const poly of polys) {
    for (let i = 0; i < poly.length - 1; i++) {
      const a = getIdx(poly[i][0], poly[i][1]);
      const b = getIdx(poly[i + 1][0], poly[i + 1][1]);
      if (a !== b) linesArr.push([a, b]);
    }
  }
  if (verts.length >= 2 && linesArr.length >= 1) {
    consOut.push({ name: CN[id] ?? id, stars: verts, lines: linesArr });
  }
}

// Bright stars: magnitude <= 4.5 from the catalog, colored later by B-V.
const bright: {
  hip: number;
  ra: number;
  dec: number;
  mag: number;
  bv: number;
}[] = [];
for (const f of stars.features as any[]) {
  const mag = f.properties?.mag;
  const bv = f.properties?.bv;
  const [ra, dec] = f.geometry.coordinates; // ra_deg, dec_deg
  if (typeof mag !== "number" || mag > 3.5) continue;
  bright.push({
    hip: Number(f.id) || 0,
    ra: Math.round((ra / 15) * 1e4) / 1e4,
    dec: Math.round(dec * 1e4) / 1e4,
    mag,
    bv: typeof bv === "number" ? bv : 0.6,
  });
}
bright.sort((a, b) => a.mag - b.mag);

const header = `// AUTO-GENERATED by scripts/_gen_p21.ts — do not edit by hand.
// Source: d3-celestial (ofrohn/d3-celestial, MIT) constellation lines + Yale/Simbad
// bright-star subset (mag <= 3.5, ~288 stars). Coordinates are J2000 equatorial: RA
// converted to hours, Dec in degrees — matching the unitDir(raH, decDeg) convention
// used by engine.buildSky. Constellation Chinese names per 中国天文学会 88-constellation
// standard (Serpens split into Caput/Cauda as two features).
`;

const body =
  header +
  `export interface BrightStar {\n` +
  `  hip: number;\n  ra: number; // hours\n  dec: number; // degrees\n  mag: number;\n  bv: number; // B-V color index\n}\n\n` +
  `export const WEST_CONSTELLATIONS: { name: string; stars: [number, number, number][]; lines: [number, number][] }[] = ` +
  JSON.stringify(consOut, null, 2) +
  ";\n\n" +
  `export const WEST_BRIGHT_STARS: BrightStar[] = ` +
  JSON.stringify(bright, null, 2) +
  ";\n";

writeFileSync(
  "src/lib/cosmos/west-constellations.ts",
  body,
  "utf8",
);

console.log(
  `Wrote west-constellations.ts: ${consOut.length} constellations, ${bright.length} bright stars`,
);
