# Generate src/lib/cosmos/globular-real.ts from the Milky Way globular-cluster catalog
# (Harris 1996/2010, VizieR VII/202). Self-contained: downloads the catalog as TSV via curl
# (the sandbox proxy blocks astroquery's VizieR client but allows curl to vizier.u-strasbg.fr),
# then parses l/b (galactic deg) and Rgc (galactocentric kpc) into a TypeScript module.
# Run:  python/envs/astro/Scripts/python.exe scripts/gen_globular.py
import os
import re
import subprocess

HERE = os.path.dirname(__file__)
RAW = os.path.join(HERE, "_gc_raw.tsv")
OUT = os.path.normpath(
    os.path.join(HERE, "..", "src", "lib", "cosmos", "globular-real.ts")
)
URL = "https://vizier.u-strasbg.fr/viz-bin/asu-tsv/-?-source=VII/202&-out.max=9999"


def hms_to_deg(s: str):
    s = s.strip()
    if not s:
        return None
    p = s.split()
    if len(p) < 2:
        return None
    return (float(p[0]) + float(p[1]) / 60 + float(p[2]) / 3600) * 15


def dms_to_deg(s: str):
    s = s.strip()
    if not s:
        return None
    sign = -1 if s[0] == "-" else 1
    s = s.lstrip("+-")
    p = s.split()
    return sign * (abs(float(p[0])) + float(p[1]) / 60 + float(p[2]) / 3600)


def main():
    print("downloading VII/202 from", URL)
    subprocess.run(["curl", "-sL", "--max-time", "90", URL, "-o", RAW], check=True)
    try:
        parse()
    finally:
        if os.path.exists(RAW):
            os.remove(RAW)  # temp download, not committed


def parse():
    with open(RAW, encoding="utf-8", errors="replace") as f:
        lines = [ln.rstrip("\n") for ln in f]
    header_idx = next(
        (i for i, ln in enumerate(lines) if ln.startswith("ID\t") or ln.startswith("ID ")),
        None,
    )
    assert header_idx is not None, "header row not found"
    cols = lines[header_idx].split("\t")
    ci = {c: i for i, c in enumerate(cols)}
    i_id = ci.get("ID", 0)
    i_l = ci.get("GLON", 3)
    i_b = ci.get("GLAT", 4)
    i_rgc = ci.get("Rgc", 6)
    i_vt = ci.get("Vt", 7)

    rows = []
    for ln in lines[header_idx + 1 :]:
        if not ln.strip() or ln.startswith("#"):
            continue
        f = ln.split("\t")
        if len(f) < max(i_l, i_b, i_rgc) + 1:
            continue
        nm = f[i_id].strip()
        try:
            l = float(f[i_l])
            b = float(f[i_b])
            rgc = float(f[i_rgc])
        except ValueError:
            continue
        if rgc <= 0 or rgc > 300:
            continue
        vt = None
        try:
            vt = float(f[i_vt])
        except (ValueError, IndexError):
            vt = None
        rows.append((nm, l, b, rgc, vt))

    print(f"parsed {len(rows)} globular clusters")
    out = []
    out.append("// Auto-generated by scripts/gen_globular.py — Milky Way globular clusters")
    out.append("// Source: Harris 1996/2010 catalog (VizieR VII/202), pulled as TSV from")
    out.append("// vizier.u-strasbg.fr. l/b = galactic (deg), d = galactocentric distance (kpc, Rgc).")
    out.append("// Real data; do not edit by hand.")
    out.append("")
    out.append("export interface GlobularData {")
    out.append("  /** Cluster identification (NGC/IC/Pal/Terzan …) */")
    out.append("  n: string;")
    out.append("  /** Galactic longitude (deg) */")
    out.append("  l: number;")
    out.append("  /** Galactic latitude (deg) */")
    out.append("  b: number;")
    out.append("  /** Galactocentric distance (kpc) */")
    out.append("  d: number;")
    out.append("  /** Integrated V magnitude if present */")
    out.append("  v?: number;")
    out.append("}")
    out.append("")
    out.append("export const GLOBULAR_CLUSTERS: GlobularData[] = [")

    def esc(s: str) -> str:
        return s.replace("\\", "\\\\").replace('"', '\\"')

    for nm, l, b, d, vt in rows:
        if vt is not None:
            out.append(f'  {{ n: "{esc(nm)}", l: {l:.4f}, b: {b:.4f}, d: {d:.3f}, v: {vt:.2f} }},')
        else:
            out.append(f'  {{ n: "{esc(nm)}", l: {l:.4f}, b: {b:.4f}, d: {d:.3f} }},')
    out.append("];")
    out.append("")
    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write("\n".join(out))
    print(f"wrote {OUT} ({len(rows)} clusters)")


if __name__ == "__main__":
    main()
